/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopVendorsRouteImport } from './routes/shop-vendors'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as IndexRouteImport } from './routes/index'

const ShopVendorsRoute = ShopVendorsRouteImport.update({
  id: '/shop-vendors',
  path: '/shop-vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loans': typeof LoansRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/shop-vendors': typeof ShopVendorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loans': typeof LoansRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/shop-vendors': typeof ShopVendorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/loans': typeof LoansRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/shop-vendors': typeof ShopVendorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/loans' | '/orders' | '/profile' | '/shop-vendors'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/loans' | '/orders' | '/profile' | '/shop-vendors'
  id: '__root__' | '/' | '/loans' | '/orders' | '/profile' | '/shop-vendors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoansRoute: typeof LoansRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  ShopVendorsRoute: typeof ShopVendorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop-vendors': {
      id: '/shop-vendors'
      path: '/shop-vendors'
      fullPath: '/shop-vendors'
      preLoaderRoute: typeof ShopVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoansRoute: LoansRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  ShopVendorsRoute: ShopVendorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
